/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 59
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 1
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_DASH = 1,
  anon_sym_COLON = 2,
  anon_sym_BQUOTE = 3,
  anon_sym_DQUOTE = 4,
  anon_sym_ERROR = 5,
  anon_sym_MISSING = 6,
  anon_sym_COLON2 = 7,
  aux_sym_content_token1 = 8,
  sym__identifier = 9,
  sym__escape = 10,
  sym_number = 11,
  anon_sym_u2022 = 12,
  sym__space = 13,
  sym__eol = 14,
  sym_cst = 15,
  sym__line = 16,
  sym_range = 17,
  sym_position = 18,
  sym_node = 19,
  sym_text = 20,
  sym_literal = 21,
  sym_error = 22,
  sym_missing = 23,
  sym_field = 24,
  sym_content = 25,
  sym__mark = 26,
  aux_sym_cst_repeat1 = 27,
  aux_sym__line_repeat1 = 28,
  aux_sym_content_repeat1 = 29,
  alias_sym_kind = 30,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DASH] = "-",
  [anon_sym_COLON] = ":",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_ERROR] = "ERROR",
  [anon_sym_MISSING] = "MISSING",
  [anon_sym_COLON2] = ":",
  [aux_sym_content_token1] = "content_token1",
  [sym__identifier] = "_identifier",
  [sym__escape] = "_escape",
  [sym_number] = "number",
  [anon_sym_u2022] = "\u2022",
  [sym__space] = "_space",
  [sym__eol] = "_eol",
  [sym_cst] = "cst",
  [sym__line] = "_line",
  [sym_range] = "range",
  [sym_position] = "position",
  [sym_node] = "node",
  [sym_text] = "text",
  [sym_literal] = "literal",
  [sym_error] = "error",
  [sym_missing] = "missing",
  [sym_field] = "field",
  [sym_content] = "content",
  [sym__mark] = "_mark",
  [aux_sym_cst_repeat1] = "cst_repeat1",
  [aux_sym__line_repeat1] = "_line_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
  [alias_sym_kind] = "kind",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_ERROR] = anon_sym_ERROR,
  [anon_sym_MISSING] = anon_sym_MISSING,
  [anon_sym_COLON2] = anon_sym_COLON,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [sym__identifier] = sym__identifier,
  [sym__escape] = sym__escape,
  [sym_number] = sym_number,
  [anon_sym_u2022] = anon_sym_u2022,
  [sym__space] = sym__space,
  [sym__eol] = sym__eol,
  [sym_cst] = sym_cst,
  [sym__line] = sym__line,
  [sym_range] = sym_range,
  [sym_position] = sym_position,
  [sym_node] = sym_node,
  [sym_text] = sym_text,
  [sym_literal] = sym_literal,
  [sym_error] = sym_error,
  [sym_missing] = sym_missing,
  [sym_field] = sym_field,
  [sym_content] = sym_content,
  [sym__mark] = sym__mark,
  [aux_sym_cst_repeat1] = aux_sym_cst_repeat1,
  [aux_sym__line_repeat1] = aux_sym__line_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [alias_sym_kind] = alias_sym_kind,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ERROR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MISSING] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [sym__escape] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_u2022] = {
    .visible = true,
    .named = false,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym_cst] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [sym_position] = {
    .visible = true,
    .named = true,
  },
  [sym_node] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_error] = {
    .visible = true,
    .named = true,
  },
  [sym_missing] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym__mark] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_cst_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__line_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_kind] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_column = 1,
  field_end = 2,
  field_escape = 3,
  field_name = 4,
  field_row = 5,
  field_start = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_column] = "column",
  [field_end] = "end",
  [field_escape] = "escape",
  [field_name] = "name",
  [field_row] = "row",
  [field_start] = "start",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 1},
  [5] = {.index = 3, .length = 1},
  [7] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_column, 2},
    {field_row, 0},
  [2] =
    {field_escape, 0},
  [3] =
    {field_name, 0},
  [4] =
    {field_end, 4},
    {field_start, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_kind,
  },
  [4] = {
    [1] = alias_sym_kind,
  },
  [6] = {
    [2] = alias_sym_kind,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 11,
  [16] = 14,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 17,
  [25] = 25,
  [26] = 8,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '\n', 33,
        '\r', 34,
        ' ', 16,
        '"', 12,
        '-', 9,
        ':', 15,
        '\\', 17,
        '`', 11,
        0x2022, 31,
      );
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(32);
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == 'M') ADVANCE(19);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead == 0x2022) ADVANCE(31);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == 'E') ADVANCE(25);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 4:
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead == '`') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 0x2022) ADVANCE(31);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '\r') ADVANCE(34);
      if (lookahead == ' ') ADVANCE(32);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == ':') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_ERROR);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_MISSING);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON2);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_content_token1);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_content_token1);
      ADVANCE_MAP(
        '"', 29,
        '0', 29,
        '\\', 29,
        '`', 29,
        'f', 29,
        'n', 29,
        'r', 29,
        't', 29,
        'v', 29,
      );
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'G') ADVANCE(14);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'I') ADVANCE(27);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'I') ADVANCE(21);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'N') ADVANCE(18);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'O') ADVANCE(24);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'R') ADVANCE(22);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'R') ADVANCE(13);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'R') ADVANCE(23);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'S') ADVANCE(20);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == 'S') ADVANCE(26);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__escape);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_u2022);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__space);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__eol);
      if (lookahead == '\n') ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 7},
  [34] = {.lex_state = 7},
  [35] = {.lex_state = 7},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 7},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_COLON2] = ACTIONS(1),
    [aux_sym_content_token1] = ACTIONS(1),
    [sym__escape] = ACTIONS(1),
    [anon_sym_u2022] = ACTIONS(1),
    [sym__space] = ACTIONS(1),
    [sym__eol] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_cst] = STATE(37),
    [sym__line] = STATE(5),
    [sym_range] = STATE(35),
    [sym_position] = STATE(34),
    [aux_sym_cst_repeat1] = STATE(5),
    [aux_sym__line_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_number] = ACTIONS(5),
    [sym__space] = ACTIONS(7),
    [sym__eol] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(11), 1,
      anon_sym_BQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_MISSING,
    ACTIONS(17), 1,
      sym__identifier,
    ACTIONS(19), 1,
      anon_sym_u2022,
    ACTIONS(21), 1,
      sym__space,
    STATE(8), 1,
      aux_sym__line_repeat1,
    STATE(20), 1,
      sym_field,
    STATE(30), 1,
      sym__mark,
    STATE(41), 5,
      sym_node,
      sym_text,
      sym_literal,
      sym_error,
      sym_missing,
  [35] = 10,
    ACTIONS(11), 1,
      anon_sym_BQUOTE,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    ACTIONS(15), 1,
      anon_sym_MISSING,
    ACTIONS(17), 1,
      sym__identifier,
    ACTIONS(19), 1,
      anon_sym_u2022,
    ACTIONS(21), 1,
      sym__space,
    STATE(8), 1,
      aux_sym__line_repeat1,
    STATE(20), 1,
      sym_field,
    STATE(30), 1,
      sym__mark,
    STATE(55), 5,
      sym_node,
      sym_text,
      sym_literal,
      sym_error,
      sym_missing,
  [70] = 8,
    ACTIONS(5), 1,
      sym_number,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym__eol,
    STATE(3), 1,
      aux_sym__line_repeat1,
    STATE(34), 1,
      sym_position,
    STATE(35), 1,
      sym_range,
    STATE(6), 2,
      sym__line,
      aux_sym_cst_repeat1,
  [96] = 8,
    ACTIONS(5), 1,
      sym_number,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym__eol,
    STATE(3), 1,
      aux_sym__line_repeat1,
    STATE(34), 1,
      sym_position,
    STATE(35), 1,
      sym_range,
    STATE(6), 2,
      sym__line,
      aux_sym_cst_repeat1,
  [122] = 7,
    ACTIONS(33), 1,
      sym_number,
    ACTIONS(36), 1,
      sym__space,
    STATE(3), 1,
      aux_sym__line_repeat1,
    STATE(34), 1,
      sym_position,
    STATE(35), 1,
      sym_range,
    ACTIONS(31), 2,
      ts_builtin_sym_end,
      sym__eol,
    STATE(6), 2,
      sym__line,
      aux_sym_cst_repeat1,
  [146] = 8,
    ACTIONS(5), 1,
      sym_number,
    ACTIONS(7), 1,
      sym__space,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      sym__eol,
    STATE(3), 1,
      aux_sym__line_repeat1,
    STATE(34), 1,
      sym_position,
    STATE(35), 1,
      sym_range,
    STATE(4), 2,
      sym__line,
      aux_sym_cst_repeat1,
  [172] = 4,
    ACTIONS(43), 1,
      sym__space,
    STATE(8), 1,
      aux_sym__line_repeat1,
    ACTIONS(41), 2,
      anon_sym_MISSING,
      sym__identifier,
    ACTIONS(39), 3,
      anon_sym_BQUOTE,
      anon_sym_DQUOTE,
      anon_sym_u2022,
  [188] = 4,
    ACTIONS(46), 1,
      aux_sym_content_token1,
    ACTIONS(48), 1,
      sym__escape,
    STATE(11), 1,
      aux_sym_content_repeat1,
    STATE(46), 1,
      sym_content,
  [201] = 4,
    ACTIONS(50), 1,
      aux_sym_content_token1,
    ACTIONS(52), 1,
      sym__escape,
    STATE(15), 1,
      aux_sym_content_repeat1,
    STATE(48), 1,
      sym_content,
  [214] = 4,
    ACTIONS(48), 1,
      sym__escape,
    ACTIONS(54), 1,
      anon_sym_BQUOTE,
    ACTIONS(56), 1,
      aux_sym_content_token1,
    STATE(14), 1,
      aux_sym_content_repeat1,
  [227] = 1,
    ACTIONS(58), 4,
      ts_builtin_sym_end,
      sym_number,
      sym__space,
      sym__eol,
  [234] = 1,
    ACTIONS(60), 4,
      ts_builtin_sym_end,
      sym_number,
      sym__space,
      sym__eol,
  [241] = 4,
    ACTIONS(62), 1,
      anon_sym_BQUOTE,
    ACTIONS(64), 1,
      aux_sym_content_token1,
    ACTIONS(67), 1,
      sym__escape,
    STATE(14), 1,
      aux_sym_content_repeat1,
  [254] = 4,
    ACTIONS(52), 1,
      sym__escape,
    ACTIONS(54), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      aux_sym_content_token1,
    STATE(16), 1,
      aux_sym_content_repeat1,
  [267] = 4,
    ACTIONS(62), 1,
      anon_sym_DQUOTE,
    ACTIONS(72), 1,
      aux_sym_content_token1,
    ACTIONS(75), 1,
      sym__escape,
    STATE(16), 1,
      aux_sym_content_repeat1,
  [280] = 2,
    ACTIONS(80), 1,
      aux_sym_content_token1,
    ACTIONS(78), 2,
      anon_sym_BQUOTE,
      sym__escape,
  [288] = 3,
    ACTIONS(11), 1,
      anon_sym_BQUOTE,
    ACTIONS(82), 1,
      sym__eol,
    STATE(45), 1,
      sym_text,
  [298] = 3,
    ACTIONS(84), 1,
      anon_sym_COLON2,
    ACTIONS(86), 1,
      sym__space,
    ACTIONS(88), 1,
      sym__eol,
  [308] = 3,
    ACTIONS(90), 1,
      sym__identifier,
    ACTIONS(92), 1,
      anon_sym_u2022,
    STATE(58), 1,
      sym__mark,
  [318] = 3,
    ACTIONS(11), 1,
      anon_sym_BQUOTE,
    ACTIONS(94), 1,
      sym__eol,
    STATE(51), 1,
      sym_text,
  [328] = 3,
    ACTIONS(96), 1,
      anon_sym_DASH,
    ACTIONS(98), 1,
      sym__space,
    STATE(26), 1,
      aux_sym__line_repeat1,
  [338] = 3,
    ACTIONS(11), 1,
      anon_sym_BQUOTE,
    ACTIONS(100), 1,
      sym__eol,
    STATE(53), 1,
      sym_text,
  [348] = 2,
    ACTIONS(80), 1,
      aux_sym_content_token1,
    ACTIONS(78), 2,
      anon_sym_DQUOTE,
      sym__escape,
  [356] = 3,
    ACTIONS(11), 1,
      anon_sym_BQUOTE,
    ACTIONS(102), 1,
      sym__eol,
    STATE(54), 1,
      sym_text,
  [366] = 3,
    ACTIONS(39), 1,
      anon_sym_DASH,
    ACTIONS(104), 1,
      sym__space,
    STATE(26), 1,
      aux_sym__line_repeat1,
  [376] = 2,
    ACTIONS(107), 1,
      sym__space,
    ACTIONS(109), 1,
      sym__eol,
  [383] = 2,
    ACTIONS(111), 1,
      sym__space,
    ACTIONS(113), 1,
      sym__eol,
  [390] = 2,
    ACTIONS(5), 1,
      sym_number,
    STATE(36), 1,
      sym_position,
  [397] = 2,
    ACTIONS(115), 1,
      anon_sym_ERROR,
    ACTIONS(117), 1,
      sym__identifier,
  [404] = 2,
    ACTIONS(13), 1,
      anon_sym_DQUOTE,
    STATE(50), 1,
      sym_literal,
  [411] = 1,
    ACTIONS(119), 2,
      sym__identifier,
      anon_sym_u2022,
  [416] = 2,
    ACTIONS(121), 1,
      sym__space,
    ACTIONS(123), 1,
      sym__eol,
  [423] = 2,
    ACTIONS(125), 1,
      sym__space,
    STATE(22), 1,
      aux_sym__line_repeat1,
  [430] = 2,
    ACTIONS(127), 1,
      sym__space,
    STATE(2), 1,
      aux_sym__line_repeat1,
  [437] = 1,
    ACTIONS(129), 1,
      sym__space,
  [441] = 1,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
  [445] = 1,
    ACTIONS(133), 1,
      sym__space,
  [449] = 1,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
  [453] = 1,
    ACTIONS(137), 1,
      sym__eol,
  [457] = 1,
    ACTIONS(139), 1,
      sym__eol,
  [461] = 1,
    ACTIONS(141), 1,
      sym__eol,
  [465] = 1,
    ACTIONS(143), 1,
      sym__space,
  [469] = 1,
    ACTIONS(145), 1,
      anon_sym_COLON2,
  [473] = 1,
    ACTIONS(147), 1,
      sym__eol,
  [477] = 1,
    ACTIONS(149), 1,
      anon_sym_BQUOTE,
  [481] = 1,
    ACTIONS(151), 1,
      sym_number,
  [485] = 1,
    ACTIONS(153), 1,
      anon_sym_DQUOTE,
  [489] = 1,
    ACTIONS(155), 1,
      sym__space,
  [493] = 1,
    ACTIONS(157), 1,
      sym__eol,
  [497] = 1,
    ACTIONS(159), 1,
      sym__eol,
  [501] = 1,
    ACTIONS(161), 1,
      sym__space,
  [505] = 1,
    ACTIONS(163), 1,
      sym__eol,
  [509] = 1,
    ACTIONS(165), 1,
      sym__eol,
  [513] = 1,
    ACTIONS(167), 1,
      sym__eol,
  [517] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
  [521] = 1,
    ACTIONS(169), 1,
      anon_sym_COLON,
  [525] = 1,
    ACTIONS(171), 1,
      sym__identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 122,
  [SMALL_STATE(7)] = 146,
  [SMALL_STATE(8)] = 172,
  [SMALL_STATE(9)] = 188,
  [SMALL_STATE(10)] = 201,
  [SMALL_STATE(11)] = 214,
  [SMALL_STATE(12)] = 227,
  [SMALL_STATE(13)] = 234,
  [SMALL_STATE(14)] = 241,
  [SMALL_STATE(15)] = 254,
  [SMALL_STATE(16)] = 267,
  [SMALL_STATE(17)] = 280,
  [SMALL_STATE(18)] = 288,
  [SMALL_STATE(19)] = 298,
  [SMALL_STATE(20)] = 308,
  [SMALL_STATE(21)] = 318,
  [SMALL_STATE(22)] = 328,
  [SMALL_STATE(23)] = 338,
  [SMALL_STATE(24)] = 348,
  [SMALL_STATE(25)] = 356,
  [SMALL_STATE(26)] = 366,
  [SMALL_STATE(27)] = 376,
  [SMALL_STATE(28)] = 383,
  [SMALL_STATE(29)] = 390,
  [SMALL_STATE(30)] = 397,
  [SMALL_STATE(31)] = 404,
  [SMALL_STATE(32)] = 411,
  [SMALL_STATE(33)] = 416,
  [SMALL_STATE(34)] = 423,
  [SMALL_STATE(35)] = 430,
  [SMALL_STATE(36)] = 437,
  [SMALL_STATE(37)] = 441,
  [SMALL_STATE(38)] = 445,
  [SMALL_STATE(39)] = 449,
  [SMALL_STATE(40)] = 453,
  [SMALL_STATE(41)] = 457,
  [SMALL_STATE(42)] = 461,
  [SMALL_STATE(43)] = 465,
  [SMALL_STATE(44)] = 469,
  [SMALL_STATE(45)] = 473,
  [SMALL_STATE(46)] = 477,
  [SMALL_STATE(47)] = 481,
  [SMALL_STATE(48)] = 485,
  [SMALL_STATE(49)] = 489,
  [SMALL_STATE(50)] = 493,
  [SMALL_STATE(51)] = 497,
  [SMALL_STATE(52)] = 501,
  [SMALL_STATE(53)] = 505,
  [SMALL_STATE(54)] = 509,
  [SMALL_STATE(55)] = 513,
  [SMALL_STATE(56)] = 517,
  [SMALL_STATE(57)] = 521,
  [SMALL_STATE(58)] = 525,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cst, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cst, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cst, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_cst_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cst_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cst_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__line_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__line_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 4, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 1, 0, 3),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 1, 0, 3),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 2, 0, 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 1, 0, 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 3, 0, 4),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_error, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 4, 0, 6),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__line_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_error, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 2, 0, 4),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 5),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 3, 0, 6),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 5, 0, 7),
  [131] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_position, 3, 0, 2),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cst, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 3, 0, 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_missing, 4, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 4, 0, 4),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_error, 4, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 5, 0, 6),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cst(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
