name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
      - .github/workflows/ci.yml
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
      - .github/workflows/ci.yml

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    if: >-
      !github.event.repository.is_template &&
      github.event.head_commit.message != 'Initial commit'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Run tests
        uses: tree-sitter/parser-test-action@v2
        with:
          generate: false
          test-rust: true
